// <auto-generated />
using System;
using DeliveryService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DeliveryService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604053200_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DeliveryService.Models.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("DeliveryService.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Все"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Напитки"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Десерты"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Горячее"
                        });
                });

            modelBuilder.Entity("DeliveryService.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_At = new DateTime(2026, 6, 4, 5, 31, 59, 922, DateTimeKind.Utc).AddTicks(7568),
                            Email = "admin@delivery.ru",
                            Name = "admin",
                            Password = "admin",
                            Phone = "00000000000",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("DeliveryService.Models.Courier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CourierPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Current_Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Current_Lon")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vehicle_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Couriers");
                });

            modelBuilder.Entity("DeliveryService.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriesId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriesId = 2,
                            Description = "Ароматный американо",
                            ImageUrl = "pack://application:,,,/Images/coffee.png",
                            Price = 150.00m,
                            Title = "Кофе",
                            Weight = 200
                        },
                        new
                        {
                            Id = 2,
                            CategoriesId = 3,
                            Description = "Нежный сливочный чизкейк",
                            ImageUrl = "pack://application:,,,/Images/cheesecake.png",
                            Price = 350.00m,
                            Title = "Чизкейк",
                            Weight = 150
                        },
                        new
                        {
                            Id = 3,
                            CategoriesId = 3,
                            Description = "Свежий слоёный круассан",
                            ImageUrl = "pack://application:,,,/Images/croissant.png",
                            Price = 180.00m,
                            Title = "Круассан",
                            Weight = 100
                        },
                        new
                        {
                            Id = 4,
                            CategoriesId = 4,
                            Description = "Узбекский плов с бараниной",
                            ImageUrl = "pack://application:,,,/Images/plov.png",
                            Price = 450.00m,
                            Title = "Плов",
                            Weight = 400
                        },
                        new
                        {
                            Id = 5,
                            CategoriesId = 4,
                            Description = "Борщ со сметаной",
                            ImageUrl = "https://images.unsplash.com/photo-1547592180-85f173990554?w=400",
                            Price = 320.00m,
                            Title = "Борщ",
                            Weight = 400
                        },
                        new
                        {
                            Id = 6,
                            CategoriesId = 2,
                            Description = "Кофе латте с молоком",
                            ImageUrl = "https://images.unsplash.com/photo-1561047029-3000c68339ca?w=400",
                            Price = 200.00m,
                            Title = "Латте",
                            Weight = 250
                        });
                });

            modelBuilder.Entity("DeliveryService.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address_From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Address_To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BasketId")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<int?>("CourierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Lat_From")
                        .HasColumnType("double precision");

                    b.Property<double>("Lat_To")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon_From")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon_To")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CourierId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DeliveryService.Models.OrderStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Changed_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeedBack")
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistories");
                });

            modelBuilder.Entity("DeliveryService.Models.RoutePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Recorded_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("RoutePoints");
                });

            modelBuilder.Entity("DeliveryService.Models.Basket", b =>
                {
                    b.HasOne("DeliveryService.Models.Food", "Food")
                        .WithMany("Baskets")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");
                });

            modelBuilder.Entity("DeliveryService.Models.Food", b =>
                {
                    b.HasOne("DeliveryService.Models.Categories", "Categories")
                        .WithMany("Foods")
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("DeliveryService.Models.Order", b =>
                {
                    b.HasOne("DeliveryService.Models.Basket", "Basket")
                        .WithMany()
                        .HasForeignKey("BasketId");

                    b.HasOne("DeliveryService.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryService.Models.Courier", "Courier")
                        .WithMany("Orders")
                        .HasForeignKey("CourierId");

                    b.Navigation("Basket");

                    b.Navigation("Client");

                    b.Navigation("Courier");
                });

            modelBuilder.Entity("DeliveryService.Models.OrderStatusHistory", b =>
                {
                    b.HasOne("DeliveryService.Models.Order", "Order")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DeliveryService.Models.RoutePoint", b =>
                {
                    b.HasOne("DeliveryService.Models.Order", "Order")
                        .WithMany("RoutePoints")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DeliveryService.Models.Categories", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("DeliveryService.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DeliveryService.Models.Courier", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DeliveryService.Models.Food", b =>
                {
                    b.Navigation("Baskets");
                });

            modelBuilder.Entity("DeliveryService.Models.Order", b =>
                {
                    b.Navigation("RoutePoints");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
